### PR TITLE
Julia 1.0 support

### PR DESCRIPTION
**Pull request by dcjones**
Julia 1.0 support. Thankfully this one went much quicker than BioSequences or GenomicFeatures.

### CODE REVIEW

**Comment by BenJWard** [comment]
Thanks @dcjones! The release of GenomicFeatures will be v1.0.0, following how BioSequences and other mature packages have a v1.0 for julia v1.0. I've updated the require to GenomicFeatures 1.0.0, once the attobot process is done and the release merged this should start passing :)

**Comment by dcjones** [comment]
I guess if it was working on x86 before, we should make some effort to keep it working. I don't know that code very well, but I'll have a look.

**Comment by phaverty** [comment]
I'm excited to see how this works with the parsing improvements in 1.0.1!

**Comment by phaverty** [comment]
Would you mind tagging a release? :-)

**Comment by BenJWard** [comment]
Done! Just had to make sure documenter was running the doctests properly first. Turns out there was some error printing substitution matrices, likely as a result of changes to strings.

**Comment by phaverty** [comment]
Excellent!

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Pull request merged**
