### PR TITLE
Fix haskey(x::BAM.Record, y::String) (issue #20)

### PR DESCRIPTION
**Pull request by jakobnissen**
# Fixes a bug in haskey(x::BAM.Record, y::String)

## Types of changes

This PR implements the following changes:
_(Please tick any or all of the following that are applicable)_

* [ ] :sparkles: New feature (A non-breaking change which adds functionality).
* :ballot_box_with_check:  :bug: Bug fix (A non-breaking change, which fixes an issue).
* [ ] :boom: Breaking change (fix or feature that would cause existing functionality to change).

## :clipboard: Additional detail
On current master, a BAM.Record's data field can be longer than the actual record's size. The actual size is accessed by `data_size(record)`, and any extra bytes are simply ignored. Except that the functions for accessing AUX keys directly from the records data field do not check the record's size. The result is that any extra bytes will be unparsable, resulting in an obscure error. See issue #20 .
Note that this problem does not occur when operating on AuxData objects, since `data_size(record)` is called when instantiating those.
To fix this problem, I have updated `findauxtag` and `getauxvalue` to use a stop keyword, indicating when there is no more data to be read. This number is found by a call to `data_size(record`) in the relevant places.

Also, I have changed an unrelated part of the test code which used to rely on trailing whitespace to work, potentially resulting in very annoying bugs.

## :ballot_box_with_check: Checklist
Since this is a pure internal bugfix, no documentation or tests has been changed.

- :ballot_box_with_check: :art: The changes implemented is consistent with the [julia style guide](https://docs.julialang.org/en/stable/manual/style-guide/).
- [ ] :blue_book: I have updated and added relevant docstrings, in a manner consistent with the [documentation styleguide](https://docs.julialang.org/en/stable/manual/documentation/).
- [ ] :blue_book: I have added or updated relevant user and developer manuals/documentation in `docs/src/`.
- :ballot_box_with_check: :ok: There are unit tests that cover the code changes I have made.
- :ballot_box_with_check: :ok: The unit tests cover my code changes AND they pass.
- :ballot_box_with_check: :pencil: I have added an entry to the `[UNRELEASED]` section of the manually curated `CHANGELOG.md` file for this repository.
- :ballot_box_with_check: :ok: All changes should be compatible with the latest stable version of Julia.
- :ballot_box_with_check: :thought_balloon: I have commented liberally for any complex pieces of internal code.

### CODE REVIEW

**Comment by jakobnissen** [comment]
The codecov percentages makes no sense.

**Comment by BenJWard** [comment]
Yeah there's a current issue with codecov where it is systematically not counting lines as covered. Basically Julia has become too smart for its own good with the optimisations and its causing issues with coverage computation.

**Comment by BenJWard** [comment]
@jakobnissen There's one conflict preventing merge in the runtests file. Presumably caused by merging your previous PR into master, so which version is the correct one to pick?

**Comment by jakobnissen** [comment]
The conflicting lines are equivalent, but pick master to be sure nothing is changed.

**Comment by BenJWard** [comment]
Ok, when the tests pass I will merge this

**Pull request merged**
