### PR TITLE
Release/v1.0.1

### PR DESCRIPTION
**Pull request by CiaranOMara**
This PR contains some general housekeeping and CI updates.

### CODE REVIEW

**Comment by BenJWard** [comment]
@CiaranOMara Let me know when you want to merge this.

**Comment by CiaranOMara** [comment]
@BenJWard, I'm ready to commit to the merge of this PR.

**Comment by CiaranOMara** [comment]
@BenJWard, I'm sure I'm ready.

**Comment by CiaranOMara** [comment]
Hang on, just noticed that the UUID in the new Projects.toml doesn't match general.

**Comment by CiaranOMara** [comment]
@BenJWard, unless you find any other faults, this probably good enough.

**Pull request merged**
